######################################################################
# Automatically generated by qmake (3.0) Thu 23. May 12:18:03 2013
######################################################################

TEMPLATE = app
win32 { CONFIG += console }
TARGET = overload
INCLUDEPATH += .

# Input
HEADERS += constoverload.h
SOURCES += constoverload-client.cpp constoverload.cpp
