######################################################################
# Automatically generated by qmake (2.00a) Tue May 31 11:26:22 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS +=  study.h
SOURCES += study.cpp
