######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 10 00:08:37 2009
######################################################################
QT += widgets
TEMPLATE = app
TARGET = numvalidate
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputform.h
SOURCES += inputform.cpp workstudycalc.cpp
