######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 10 00:08:37 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inputform.h
SOURCES += inputform.cpp workstudycalc.cpp
