######################################################################
# Automatically generated by qmake (3.0) Wed 22. May 18:04:25 2013
######################################################################
QT += widgets
TEMPLATE = app
TARGET = form
INCLUDEPATH += .

# Input
HEADERS += inputform.h
SOURCES += inputform.cpp \
    main.cpp
