######################################################################
# Automatically generated by qmake (3.0) Wed 22. May 17:34:40 2013
######################################################################
QT += widgets
TEMPLATE = app
TARGET = messagebox
INCLUDEPATH += .

# Input
SOURCES += dialogs.cpp

HEADERS += \
    dialogs.h
