######################################################################
# Automatically generated by qmake (3.0) Thu 2. May 00:14:44 2013
######################################################################

include(../../common.pri)

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .
# Input
SOURCES += clargs.cpp
