######################################################################
# Automatically generated by qmake (3.0) Thu 23. May 12:03:14 2013
######################################################################

include(../../common.pri)

TEMPLATE = app
TARGET = fraction
INCLUDEPATH += .

# Input
HEADERS += fraction.h
SOURCES += fraction-client.cpp fraction.cpp
