######################################################################
# Automatically generated by qmake (3.0) Wed 29. May 12:31:52 2013
######################################################################

QT += widgets

TEMPLATE = app
TARGET = manual
INCLUDEPATH += .

# Input
HEADERS += order.h orderform.h
SOURCES += main.cpp order.cpp orderform.cpp
