######################################################################
# Automatically generated by qmake (3.0) Wed 22. May 17:32:17 2013
######################################################################

QT += widgets

TEMPLATE = app
TARGET = modal
INCLUDEPATH += .

# Input
SOURCES += main.cpp
