######################################################################
# Automatically generated by qmake (3.0) Thu 23. May 12:23:10 2013
######################################################################

TEMPLATE = app
win32 { CONFIG += console }
TARGET = qmap
INCLUDEPATH += .

# Input
HEADERS += textbook.h \
    textbookmap.h
SOURCES += qmap-example.cpp \
    textbook.cpp \
    textbookmap.cpp
