######################################################################
# Automatically generated by qmake (3.0) Sun 12. May 09:20:32 2013
######################################################################

TEMPLATE = app
win32 { CONFIG += console }
TARGET = complex
INCLUDEPATH += .

# Input
HEADERS += complex.h
SOURCES +=  complex.cpp \
            complex-test.cpp \
#            complex-conversions.cpp
