######################################################################
# Automatically generated by qmake (3.0) Mon 27. May 12:38:34 2013
######################################################################

TEMPLATE = app
QT += widgets
TARGET = mainwindow
INCLUDEPATH += .

# Input
HEADERS += mymainwindow.h
SOURCES += mainwindow-main.cpp mymainwindow.cpp

RESOURCES += ../../libs/icons/icons.qrc
